services:
  pg:
    image: postgres:16
    container_name: algobank-pg
    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: algobank
      POSTGRES_USER: algobank
      POSTGRES_PASSWORD: algobank_pw
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
