-- Шаг 8 · SQL-блок 2 · Q6: FULL OUTER JOIN с условием в ON.
-- Соединение: t.account_id = a.id AND t.amount_minor > 0 — положительность в ON, НЕ в WHERE!
-- Колонки: owner_name, id (транзакции), amount_minor.
-- Порядок: owner_name ASC NULLS LAST, затем id транзакции ASC NULLS LAST.
-- Раскладка 11 строк: Анна (NULL,NULL) → положительные пары Иван/Мария×2/Олег →
-- 6 отрицательных транзакций-«сирот» с NULL вместо владельца (теория §5).
-- Постановка и ожидаемый результат: docs/sqldrills/step08/README.md (Q6)
-- Напиши один SELECT ниже этой строки:
