CREATE TABLE account
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_name    VARCHAR(200) NOT NULL,
    balance_minor BIGINT       NOT NULL
);

CREATE TABLE transactions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount_minor BIGINT NOT NULL,
    description  VARCHAR(1000),
    account_id   BIGINT NOT NULL,
    CONSTRAINT fk_transactions_account
        FOREIGN KEY (account_id) REFERENCES account (id)
);
